### ISSUE TITLE
API for downloading package file?

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-cat#19]
Hi, @panstav1 
In the README I couldn't find something on the Catalogue's API for downloading the package file, but my doubt is: which `uuid` is the one to be passed, the one present in the package metadata?

**Comment by panstav1** [comment]
@jbonnet 
The endpoint of downloading is attached as 
`curl -H "Content-Type:application/zip" http://localhost:4011/api/catalogues/v2/tgo-packages/{id}`
where the `{id}` is the one returned (and attached) from the Catalogues.

**Comment by jbonnet** [comment]
Ok, @panstav1 
You mean it is the extra field added recently in the package meta-data?

**Comment by panstav1** [comment]
@jbonnet  yes. The field's name is `id`. In the download endpoint request, you just replace `{id}` with the 32-length uuid returned from the Catalogues.
