### ISSUE TITLE
Uploading arbitrary files can often cause conflicts

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-cat#22]
Hey @panstav1, @jbonnet 

I am about to finalize the integration with tng-sdk-package.

When I implemented the functionality to upload arbitrary files, e.g., the logo of a package or a MyExample TTCN-3 binary, I noticed that the catalogue checks for existence of those files and gives a 409 (conflict).

This might be problematic, because different packages might contain the same files! For example, all our test packages could contain the 5GTANGO logo.png. So it should be possible to upload the logo once for each of the uploaded packages, right?

Since we know the UUIDs of the files, one can find and delete those files when a package is deleted.

A more extreme example: Developer A has fileZ in his package. Developer B also has file Z in his package. A uploads the package. B gets an error when uploading his package because Z already exists. That should not happen ;-)

What do you think?

**Comment by jbonnet** [comment]
@mpeuster, @panstav1 I agree, no `409 - Conflict` should be given. 

1. easy solution (storage bound): create a 'folder' like (I don't know the exact implementation on the tng-cat site) named like the package (UUID?), where all files from that package is stored: a con is potentially lots of duplicated files, a pro is we have a simple isolation between different package's files;
2. clean solution (cpu bound): hash each file (equal hashes are equal files) and store only one copy of a file. Con is time/cpu cycles taken to do this, specially for fat packages, and the need to implement a 'reference count' mechanism to allow deleting the files of a package;

I'd go for 1.

**Comment by mpeuster** [comment]
I agree and 1. would be also fine for me. And I think for the size of our project and our typical use cases this is enough for now.

At the end it is up to @panstav1 how to implement it.

**Comment by panstav1** [comment]
fixed in pull request https://github.com/sonata-nfv/tng-cat/pull/23
