### ISSUE TITLE
What are package_id and package_name?

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-cat#33]
Dear @panstav1, @mpeuster 
In a package meta-data, we've got 
```json
{
    "created_at":"2018-05-16T13:00:40.235+00:00",
    ...
    "package_file_id":"a2227bcc-0ee6-41f3-85ef-40f023bc50a3",
    "package_file_name":"tmptiha8lgb.tgo",
    "package_id":null,
    "package_name":null,
    "pd":{
        ...
    },
    ...
    "uuid":"da9654bd-bfb5-4d4b-ab7d-b03a5cfd1138"
}
```

My question is: what are `package_id` and `package_name`? Are these equivalent to `package_file_id` and `package_file_name`? If they are, can we get read of them? If they aren't, who's generating them?

**Comment by panstav1** [comment]
@jbonnet 
In #32, there are deleted in the integration environment
