### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-cat#34]
Can we review the files API?
What I think would be best is something like .../packages/:uuid/files to return a list of files for the package (the existing mapping?). Then .../package/:uuid/files/:file_uuid would give the specific file. What do you think?

**Comment by mpeuster** [comment]
I like it. And for uploading files I would then suggest: `POST /packages/:uuid/files`

**Comment by jbonnet** [comment]
Exactely. @panstav1 can we have this? We need to coordinate between `tng-sdk-package` and `tng-gtk-common`...

**Comment by panstav1** [comment]
@jbonnet @mpeuster  Of course, we can have this

**Comment by panstav1** [comment]
Suggestion: In @mpeuster 's suggestion, i would suggest also to remove the "pd" field in the mappings field, sent from the unpackager, on the grounds that this is going be appended in package descriptor. What's your view on this one @jbonnet ?

**Comment by jbonnet** [comment]
I missed the `mappings` endpoint birth, but I believe it can be completely replaced by this better approach... but this is NOT the `pd` field in the data returned in the `.../packages/:package_uuid` endpoint, is it?
