### ISSUE TITLE
Package file name

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-cat#35]
@panstav1 I also think it would be nice that the package file name be preserved, i.e., when I upload package file `xyz.tgo` and later I download it, it is called `xyz.tgo`. Current tests show something like `5gtango-ns-package-example.tgo`(uploaded) and `tmpffd99yj7.tgo` (downloaded).

**Comment by mpeuster** [comment]
@jbonnet That is actually the tng-sdk-packager fault ;-) Reason is it creates a temp. name to work with the package to support parallel packaging processes of multiple packages with the same name.

I will open an issue in the packager and patch it ;-)

**Comment by mpeuster** [comment]
This issue here can be closed.

**Comment by panstav1** [comment]
@jbonnet  Yes, the file name is preserved actually in the Catalogue :) Thanks @mpeuster !
